name: spidiff
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - h5py
  - ffmpeg
  - pip:
      - anndata==0.10.9
      - scanpy==1.10.2
      - diffusers==0.29.2
      - accelerate==0.32.1
      - timm==1.0.7
      - torch-geometric==2.6.1
      - umap-learn==0.5.6
      - leidenalg==0.10.2
      - igraph==0.11.6
      - wandb==0.17.8
      - scienceplots==2.1.1
      - tqdm
      - huggingface-hub